version: '3.7'

services:

  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # - '.:/'
      - '/node_modules'
    restart: always
    init: true
    ports:
      - 3000:3000
    expose:
      - '3000'
    environment:
      - CHOKIDAR_USEPOLLING=true