import LocalizedStrings from "react-localization";

let strings = {
  en: {
    rl: "Recent Releases",
    f: "Favorites",
    so: "Sign Out",
    mh: "Conversation with Movie Assistant",
    ph: "Write your message here",
    qp: "What film genere would you like to watch?",
    pf: "Profile",
    it: "Input search text",
    un: "Username",
    lang: "Language",
    age: "Age",
    submit: "Submit",
    reset: "Reset",
    nl: "English",
    u18: "Under 18",
    o18: "Over 18",
    ar: "Age Restriction Reset.",
    al: "added to the list.",
    rel: "removed from the list.",
    lu: "List Updated.",
    nm: "No More Movies.",
  },
  es: {
    rl: "Lanzamientos recientes",
    f: "Favoritos",
    so: "Cerrar sesión",
    mh: "Conversación con Movie Assistant",
    ph: "Escribe tu mensaje aquí",
    qp: "¿Qué género de películas te gustaría ver?",
    pf: "Perfil",
    it: "Ingresar texto de búsqueda",
    un: "Nombre de usuario",
    lang: "Idioma",
    age: "Años",
    submit: "Enviar",
    reset: "Reiniciar",
    nl: "Español",
    u18: "Menores de 18 años",
    o18: "Mayores de 18",
    ar: "Restablecimiento de restricción de edad.",
    al: "agregado a la lista",
    rel: "eliminado de la lista",
    lu: "Lista actualizada",
    nm: "No más películas",
  },
  ru: {
    rl: "Последние выпуски",
    f: "Избранное",
    so: "Выйти",
    mh: "Разговор с Ассистентом фильма",
    ph: "Напишите здесь свое сообщение",
    qp: "какой жанр фильмов вы бы хотели посмотреть?",
    pf: "Профиль",
    it: "Введите текст для поиска",
    un: "Имя пользователя",
    lang: "Язык",
    age: "Возраст",
    submit: "представить",
    reset: "Сброс настроек",
    nl: "русский",
    u18: "До 18",
    o18: "Более 18",
    ar: "Сброс возрастного ограничения.",
    al: "добавлен в список.",
    rel: "удален из списка.",
    lu: "Список обновлен.",
    nm: "Больше никаких фильмов.",
  },
  fr: {
    rl: "Versions récentes",
    f: "Favoris",
    so: "Déconnexion",
    mh: "Conversation avec Movie Assistant",
    ph: "Écrivez votre message ici",
    qp: "quel genre de film aimeriez-vous regarder?",
    pf: "Profil",
    it: "Texte de recherche d'entrée",
    un: "Nom d'utilisateur",
    lang: "Langue",
    age: "Âge",
    submit: "Soumettre",
    reset: "Réinitialiser",
    nl: "français",
    u18: "Moins de 18 ans",
    o18: "Plus de 18 ans",
    ar: "Réinitialisation de la restriction d'âge.",
    al: "ajouté à la liste.",
    rel: "supprimé de la liste.",
    lu: "Liste mise à jour.",
    nm: "Plus de films.",
  },
  ko: {
    rl: "최근 출시",
    f: "즐겨 찾기",
    so: "로그 아웃",
    mh: "Movie Assistant와 대화",
    ph: "여기에 메시지 작성",
    qp: "어떤 영화 장르를보고 싶습니까?",
    pf: "프로필",
    it: "검색 텍스트 입력",
    un: "사용자 이름",
    lang: "언어",
    age: "나이",
    submit: "제출",
    reset: "초기화",
    nl: "한국어",
    u18: "18 세 미만",
    o18: "18 이상",
    ar: "연령 제한 재설정.",
    al: "목록에 추가되었습니다.",
    rel: "목록에서 제거됨.",
    lu: "목록 업데이트 됨.",
    nm: "더 이상 영화 없음.",
  },
  zh: {
    rl: "最新版本",
    f: "收藏夹",
    so: "退出",
    mh: "与电影助手对话",
    ph: "在这里写您的信息",
    qp: "您想看什么类型的电影",
    pf: "个人资料",
    it: "输入搜索文字",
    un: "用户名",
    lang: "语言",
    age: "年龄",
    submit: "提交",
    reset: "重启",
    nl: "简体中文",
    u18: "18岁以下",
    o18: "年满18岁",
    ar: "年龄限制重置。",
    al: "添加到列表中。",
    rel: "已从列表中删除。",
    lu: "列表已更新。",
    nm: "没有更多的电影。",
  },
};

export default strings;
